Adding about.html page per instructions for ROLE 2
voidmaelstrom/collab-test-repo pull request #2
Opened 2022-04-26 20:20 UTC by sagreenxyz

Hey!  Just submitting a pull request as per instructions for ROLE 2 of this activity.  TY!

2022-04-26 21:22 UTC, voidmaelstrom requested changes
One minor thing; other than that, looks good!

2022-04-26 21:22 UTC, voidmaelstrom commented on about.html
> +    <title>ABout</title>
Just a small thing, but lowercase the 'B' here. Thanks!

2022-04-26 23:43 UTC, AydaMkd approved these changes

2022-04-27 00:23 UTC, voidmaelstrom approved these changes

2022-04-27 00:26 UTC, merged

2022-10-11 08:27 UTC, sagreenxyz commented
Ah ..  will do. That drives me nuts too

On Tue, Apr 26, 2022, 4:22 PM Bradley Stouffer ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> One minor thing; other than that, looks good!
> ------------------------------
>
> In about.html
> <https://github.com/voidmaelstrom/collab-test-repo/pull/2#discussion_r859155774>
> :
>
> > @@ -0,0 +1,17 @@
> +<!DOCTYPE html>
> +<html lang="en">
> +
> +<head>
> +    <meta charset="UTF-8" />
> +    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
> +    <title>ABout</title>
>
> Just a small thing, but lowercase the 'B' here. Thanks!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/voidmaelstrom/collab-test-repo/pull/2#pullrequestreview-954017876>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAHQJ5CIELEJDZNADTLDLCLVHBNAPANCNFSM5UM7KZJQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>